### ISSUE TITLE
What is the name for someone who can merge?

### ISSUE THREAD

**Issue by rickecon** [OpenRG/WB-India#7]
@jdebacker Do you know what the official name is of someone who can merge? @gauravsgahlot

**Comment by navneeraj** [comment]
codeowners

**Comment by patidarkapil** [comment]
I think it codeowner

**Comment by abhishekecon** [comment]
codeowners

**Comment by sanyamjoshi** [comment]
Controller

**Comment by rickecon** [comment]
I know that "Collaborators" can be given merge access to a repository.

**Comment by shekharkhetan** [comment]
proficient programmer
